// permissions
export const ADD_DATA = 'ADD_DATA';
export const TOGGLE_DIALOG = 'TOGGLE_DIALOG';
export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAIL = 'FETCH_DATA_FAIL';
export const ADD_PERMISSION = 'ADD_PERMISSION';
export const ADD_PERMISSION_SUCCESS = 'ADD_PERMISSION_SUCCESS';
export const ADD_PERMISSION_FAIL = 'ADD_PERMISSION_FAIL';
export const REMOVE_PERMISSION = 'REMOVE_PERMISSION';
export const REMOVE_PERMISSION_SUCCESS = 'REMOVE_PERMISSION_SUCCESS';
export const REMOVE_PERMISSION_FAIL = 'REMOVE_PERMISSION_FAIL';
export const EDIT_PERMISSION = 'EDIT_PERMISSION';
export const EDIT_PERMISSION_SUCCESS = 'EDIT_PERMISSION_SUCCESS';
export const EDIT_PERMISSION_FAIL = 'EDIT_PERMISSION_FAIL';

// settings
export const CHANGE_RATE = 'CHANGE_RATE';
